- name: Update all Debian/Ubuntu packages to their latest version
  hosts: New_Devices
  become: true
  become_user: root
  tasks:
  
      - name: update apt
        ansible.builtin.apt:
        update_cache: true

      - name: install btop
        ansible.builtin.apt:
        name: btop
