- name: install my tools
  hosts: ubuntu_servers
  become: true
  become_user: root
  tasks:
      - name: install btop
        ansible.builtin.apt:
          pkg:
          - jq
          - btop
          - ipcalc
          - zsh
          - git
          - whois
          - nmap
          - speedtest-cli
          - cmatrix
          - bind9-dnsutils
          - htop
          - iftop
          - asn
          - curl
          - ncat
          - bind9-host
          - grepcidr
          - aha
          - mtr-tiny
          - nethogs
          - net-tools
          - duf
          - nmon
          - bat