- name: My first play
  hosts: pi5test
  become: true
  become_user: root
  tasks:
  
    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: foo
        update_cache: yes 
