- name: My first play
  hosts: New_Devices
  tasks:
    
    - name: scripts folder in home folder
      ansible.builtin.file:
        path: ~/scripts2
        state: directory
        
    - name: creat IP checker
      ansible.builtin.file:
        path: ~/scripts2/whatsmyip.sh
        state: touch
        mode: 0777
    -name: add to whatsmyip.sh
     lineinfile:
       path:"~/scripts2/whatsmyip.sh"
       line: curl icanhazip.com
       insertbefore: BOF

    - name: clone my init script from gh
      ansible.builtin.git:
        repo: https://github.com/armangabric/init.git
        dest: ~/github
        #single_branch: yes
        #version: master

    #- name: check public ip
    #  ansible.builtin.script: /home/arman/scripts/whatsmyip.sh

