- name: My first play
  hosts: pi_servers
  tasks:
    
    - name: scripts folder in home folder
      ansible.builtin.file:
        path: ~/scripts2
        state: directory
        
    - name: scripts folder in home folder
      ansible.builtin.file:
        path: ~/scripts2/whatsmyip.sh
        state: touch
        mode: 0777

    - name: clone my init script from gh
      ansible.builtin.git:
        repo: https://github.com/armangabric/init.git
        dest: ~/github
        #single_branch: yes
        #version: master
