- name: Updates servers using aginit.sh
  hosts: New_Devices
  tasks:
    
    - name: clone my init script from gh
      ansible.builtin.git:
        repo: https://github.com/armangabric/init.git
        dest: ~/github
        #single_branch: yes
        #version: master

    - name: change perm.
      ansible.builtin.file:
        path: ~/github/aginit.sh
        state: touch
        mode: 0775
            
    - name: run it
      ansible.builtin.script: 
        cmd: ~/github/aginit.sh
