- name: Update all Debian/Ubuntu packages to their latest version
  hosts: pi_servers
  beome: true
  become_user: root
  tasks:
    
      - name: Update
        ansible.builtin.apt:
          name: "*"
          state: latest
